name: Knock
on:
  # Triggers the workflow on a schedule
  schedule:
    - cron: '0 */12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  knock:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install Node Dependencies
        run: npm install
      - name: Knock
        run: |
          node .
        env:
          AEM_HOST: ${{ secrets.AEM_HOST }}
          AEM_PASSWORD: ${{ secrets.AEM_PASSWORD }}
          AEM_USER: ${{ secrets.AEM_USER }}
